version: '2'
services:
  backend1:
    build: ./sample-backend
    environment: 
      - "PORT=3000"
      - "CONTEXT_PATH=/backend1"
      - "MESSAGE=From backend 1"
    ports: 
      - "3000:3000"
  backend2a:
    build: ./sample-backend
    environment: 
      - "PORT=3001"
      - "CONTEXT_PATH=/backend2"
      - "MESSAGE=From backend 2A"
  backend2b:
    build: ./sample-backend
    environment: 
      - "PORT=3002"
      - "CONTEXT_PATH=/backend2"
      - "MESSAGE=From backend 2B"
  backend2c:
    build: ./sample-backend
    environment: 
      - "PORT=3003"
      - "CONTEXT_PATH=/backend2"
      - "MESSAGE=From backend 2C"
  backend2d:
    build: ./sample-backend
    environment: 
      - "PORT=3004"
      - "CONTEXT_PATH=/backend2"
      - "MESSAGE=From backend 2D"
  redis:
    image: redis:6-alpine
  proxy:
    build: ./proxy
    depends_on: 
      - redis
    volumes: 
      - "./config.json:/app/config.json"
    environment: 
      - "REDIS_ADDRESS=redis:6379"
      - "DEBUG=false"
    ports: 
      - "8080:8080"
    
      
